rules = [
  OrganizeImports
  DisableSyntax
]

OrganizeImports.targetDialect = Scala3
OrganizeImports.removeUnused = false
OrganizeImports.groupedImports = Explode
OrganizeImports.groups = ["io.worxbend.", "re:javax?\\.", "scala.", "*"]

DisableSyntax.noVars = true
DisableSyntax.noReturns = true
DisableSyntax.noNulls = true
DisableSyntax.noThrows = false
DisableSyntax.noWhileLoops = true
