version = "3.11.5"
runner.dialect = scala3
maxColumn = 110
align.preset = most
docstrings.style = Asterisk
docstrings.wrap = no
docstrings.blankFirstLine = yes
rewrite.rules = [AvoidInfix, RedundantParens, SortModifiers, Imports]
rewrite.imports.sort = scalastyle
rewrite.sortModifiers.order = [implicit, final, sealed, abstract, private, protected, lazy, override]
rewrite.trailingCommas.style = always
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes
newlines.beforeMultiline = fold
newlines.afterCurlyLambdaParams = squash
assumeStandardLibraryStripMargin = true
